name: 'Setup Siv3D'
description: 'This action sets up Siv3D'
inputs:
  version:
    description: 'Siv3D version. [latest,vX.Y.Z]'
    default: 'latest'
  web: 
    description: 'setup Siv3D for web.'
    default: false
    type: boolean
  emscripten-version:
    description: 'Emscripten version.'
  github_token:
    description: 'GitHub token'

outputs:
  version:
    description: 'installed Siv3D version'
    value: ${{ steps.install.outputs.version }}
  path:
    description: 'installed Siv3D path'
    value: ${{ steps.install.outputs.path }}

runs:
  using: 'composite'
  steps:
    - name: Resolve version
      uses: srz-zumix/retry-run-action@v0
      id: resolve
      env:
        INPUTS_VERSION: ${{ inputs.version }}
        INPUTS_GITHUB_TOKEN: ${{ inputs.github_token }}
        GITHUB_TOKEN: ${{ github.token }}
        SIV3D_REPO: ${{ inputs.web == 'true' && 'nokotan/OpenSiv3D' || 'Siv3D/OpenSiv3D' }}
      with:
        retry: 5
        interval: 30
        run: |
          "${GITHUB_ACTION_PATH}/resolve.sh"
    - uses: actions/cache@v4
      with:
        path: |
          ${{ steps.resolve.outputs.install-path }}
        key: ${{ runner.os }}-siv3d-${{ steps.resolve.outputs.version }}
    - uses: mymindstorm/setup-emsdk@v14
      with:
        version: ${{ inputs.emscripten-version }}
      if: inputs.web == 'true'
    - name: Install Siv3D
      shell: bash
      id: install
      env:
        INPUTS_VERSION: ${{ steps.resolve.outputs.version }}
        INPUTS_GITHUB_TOKEN: ${{ inputs.github_token }}
        GITHUB_TOKEN: ${{ github.token }}
        SIV3D_REPO: ${{ inputs.web == 'true' && 'nokotan/OpenSiv3D' || 'Siv3D/OpenSiv3D' }}
      run: |
        if [ "${{ inputs.web }}" = "true" ]; then
          "${GITHUB_ACTION_PATH}/install-web.sh"
          exit 0
        fi
        if [ "${{ runner.os }}" = "macOS" ]; then
          "${GITHUB_ACTION_PATH}/install-macos.sh"
          exit 0
        fi
        if [ "${{ runner.os }}" = "Linux" ]; then
          INSTALL_PATH=/usr/local "${GITHUB_ACTION_PATH}/install-linux.sh"
          exit 0
        fi

branding:
  icon: 'book'
  color: 'blue'
