name: SelfTest
on:
  pull_request:

jobs:
  self-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: 
          - ubuntu-latest
          - macos-latest
        web:
          - false
          - true
    steps:
    - name: clone
      uses: actions/checkout@v4
    - uses: ./
      id: setup
      with:
        web: ${{ matrix.web }}
    - run: |
        test -n "${{ steps.setup.outputs.version }}"
